routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\CenterProductController;
use App\Http\Controllers\CentersController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\TransfersController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

Route::get('/login', [LoginController::class, 'show'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'login'])->middleware('guest');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', HomeController::class)->name('home');
    Route::resource('centers', CentersController::class);
    Route::resource('products', ProductsController::class);
    Route::resource('centers.products', CenterProductController::class)->except(['index', 'show']);
    Route::resource('transfers', TransfersController::class)->except(['show', 'edit', 'destroy']);
    Route::resource('users', UsersController::class)->except(['show', 'edit', 'update']);
    Route::post('/logout', LogoutController::class)->name('logout');
});

app/Models/Center.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Center extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'address',
        'city',
        'state',
        'zip',
    ];

    public function products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class)->withPivot('quantity');
    }

    public function sentTransfers(): HasMany
    {
        return $this->hasMany(Transfer::class, 'sender_id');
    }

    public function receivedTransfers(): HasMany
    {
        return $this->hasMany(Transfer::class, 'receiver_id');
    }

    public function users(): HasMany
    {
        return $this->hasMany(User::class);
    }
}

app/Models/Product.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'price',
        'category',
    ];

    public function transfers(): HasMany
    {
        return $this->hasMany(Transfer::class);
    }

    public function centers(): BelongsToMany
    {
        return $this->belongsToMany(Center::class)->withPivot('quantity');
    }
}

app/Http/Controllers/CentersController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Middleware\Admin;
use App\Http\Requests\CenterRequest;
use App\Models\Center;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class CentersController extends Controller
{
    public function __construct()
    {
        $this->middleware(Admin::class)->only(['create', 'store']);
    }

    public function index(): View
    {
        $centers = Center::orderBy('name')->get();

        return view('centers.index', compact('centers'));
    }

    public function show(Center $center): View
    {
        return view('centers.show', compact('center'));
    }

    public function create(): View
    {
        return view('centers.create');
    }

    public function store(CenterRequest $request): RedirectResponse
    {
        Center::create($request->validated());

        return redirect()
            ->route('centers.index')
            ->with('message', 'Center created successfully');
    }

    public function edit(Center $center): View
    {
        return view('centers.edit', compact('center'));
    }

    public function update(CenterRequest $request, Center $center): RedirectResponse
    {
        $center->update($request->validated());

        return redirect()
            ->route('centers.index')
            ->with('message', 'Center updated successfully');
    }

    public function destroy(Center $center): RedirectResponse
    {
        $center->delete();

        return redirect()
            ->route('centers.index')
            ->with('message', 'Center deleted successfully');
    }
}

app/Http/Controllers/ProductsController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Enums\ProductCategory;
use App\Http\Middleware\Admin;
use App\Http\Requests\ProductRequest;
use App\Models\Product;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class ProductsController extends Controller
{
    public function __construct()
    {
        $this->middleware(Admin::class)->only(['create', 'store', 'edit', 'update', 'destroy']);
    }

    public function index(): View
    {
        $products = Product::orderBy('name')->paginate(10);

        return view('products.index', compact('products'));
    }

    public function show(Product $product): View
    {
        return view('products.show', compact('product'));
    }

    public function create(): View
    {
        $categories = ProductCategory::cases();

        return view('products.create', compact('categories'));
    }

    public function store(ProductRequest $request): RedirectResponse
    {
        Product::create($request->validated());

        return redirect()
            ->route('products.index')
            ->with('message', 'Product created successfully');
    }

    public function edit(Product $product): View
    {
        $categories = ProductCategory::cases();

        return view('products.edit', compact('product', 'categories'));
    }

    public function update(ProductRequest $request, Product $product): RedirectResponse
    {
        $product->update($request->validated());

        return redirect()
            ->route('products.index')
            ->with('message', 'Product updated successfully');
    }

    public function destroy(Product $product): RedirectResponse
    {
        $product->delete();

        return redirect()
            ->route('products.index')
            ->with('message', 'Product deleted successfully');
    }
}

resources/views/centers/products/create.blade.php
@extends('layouts.app')

@section('title', "Add a new product")

@section('content')
    <form action="{{ route('centers.products.store', $center->id) }}" method="POST">
        @csrf

        <div class="mb-3">
            <label for="product_id" class="form-label">Product</label>
            <select class="form-select" id="product_id" name="product_id">
                @foreach($products as $product)
                    <option value="{{ $product->id }}" {{ $product->id === old('product_id') ? 'selected' : '' }}>{{ $product->name }}</option>
                @endforeach
            </select>
            @error('product_id')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="quantity" class="form-label">Quantity</label>
            <input type="number" class="form-control" id="quantity" name="quantity" value="{{ old('quantity') }}">
            @error('quantity')
            <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">Add to center</button>
    </form>
@endsection

resources/views/centers/products/edit.blade.php
@extends('layouts.app')

@section('title', "Update {$product->name}'s quantity for {$center->name}")

@section('content')
    <form action="{{ route('centers.products.update', [$center->id, $product->id]) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="mb-3">
            <label for="product_id" class="form-label">Product</label>
            <select class="form-select" id="product_id" name="product_id">
                <option value="{{ $product->id }}" {{ $product->id === old('product_id') ? 'selected' : '' }}>{{ $product->name }}</option>
            </select>
            @error('product_id')
            <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="quantity" class="form-label">Quantity</label>
            <input type="number" class="form-control" id="quantity" name="quantity" value="{{ old('quantity', $pivot->quantity) }}">
            @error('quantity')
            <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">Update product's quantity</button>
    </form>
@endsection