routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\CenterProductController;
use App\Http\Controllers\CentersController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\TransfersController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

Route::get('/login', [LoginController::class, 'show'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'login'])->middleware('guest');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', HomeController::class)->name('home');
    Route::resource('centers', CentersController::class);
    Route::resource('products', ProductsController::class);
    Route::resource('centers.products', CenterProductController::class)->except(['index', 'show']);
    Route::resource('transfers', TransfersController::class)->except(['show', 'edit', 'destroy']);
    Route::resource('users', UsersController::class)->except(['show', 'edit', 'update']);
    Route::post('/logout', LogoutController::class)->name('logout');
});

app/Models/Center.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Center extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'address',
        'city',
        'state',
        'zip',
    ];

    public function products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class)->withPivot('quantity');
    }

    public function sentTransfers(): HasMany
    {
        return $this->hasMany(Transfer::class, 'sender_id');
    }

    public function receivedTransfers(): HasMany
    {
        return $this->hasMany(Transfer::class, 'receiver_id');
    }

    public function users(): HasMany
    {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/CentersController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Middleware\Admin;
use App\Http\Requests\CenterRequest;
use App\Models\Center;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class CentersController extends Controller
{
    public function __construct()
    {
        $this->middleware(Admin::class)->only(['create', 'store']);
    }

    public function index(): View
    {
        $centers = Center::orderBy('name')->get();

        return view('centers.index', compact('centers'));
    }

    public function show(Center $center): View
    {
        return view('centers.show', compact('center'));
    }

    public function create(): View
    {
        return view('centers.create');
    }

    public function store(CenterRequest $request): RedirectResponse
    {
        Center::create($request->validated());

        return redirect()
            ->route('centers.index')
            ->with('message', 'Center created successfully');
    }

    public function edit(Center $center): View
    {
        return view('centers.edit', compact('center'));
    }

    public function update(CenterRequest $request, Center $center): RedirectResponse
    {
        $center->update($request->validated());

        return redirect()
            ->route('centers.index')
            ->with('message', 'Center updated successfully');
    }

    public function destroy(Center $center): RedirectResponse
    {
        $center->delete();

        return redirect()
            ->route('centers.index')
            ->with('message', 'Center deleted successfully');
    }
}

resources/views/centers/create.blade.php
@extends('layouts.app')

@section('title', 'Create a new center')

@section('content')
    <form action="{{ route('centers.store') }}" method="POST">
        @csrf

        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}">
            @error('name')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="address" class="form-label">Address</label>
            <input type="text" class="form-control" id="address" name="address" value="{{ old('address') }}">
            @error('address')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="city" class="form-label">City</label>
            <input type="text" class="form-control" id="city" name="city" value="{{ old('city') }}">
            @error('city')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="state" class="form-label">State</label>
            <input type="text" class="form-control" id="state" name="state" value="{{ old('state') }}">
            @error('state')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="zip" class="form-label">Zip</label>
            <input type="text" class="form-control" id="zip" name="zip" value="{{ old('zip') }}">
            @error('zip')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/centers/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit a center')

@section('content')
    <form action="{{ route('centers.update', $center->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ $center->name }}">
            @error('name')
            <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="address" class="form-label">Address</label>
            <input type="text" class="form-control" id="address" name="address" value="{{ $center->address }}">
            @error('address')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="city" class="form-label">City</label>
            <input type="text" class="form-control" id="city" name="city" value="{{ $center->city }}">
            @error('city')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="state" class="form-label">State</label>
            <input type="text" class="form-control" id="state" name="state" value="{{ $center->state }}">
            @error('state')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="zip" class="form-label">Zip</label>
            <input type="text" class="form-control" id="zip" name="zip" value="{{ $center->zip }}">
            @error('zip')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/centers/index.blade.php
@extends('layouts.app')

@section('title', "Centers ({$centers->count()})")

@section('content')
    @if(auth()->user()->isAdmin())
        <a class="btn btn-primary float-end mb-4" href="{{ route('centers.create') }}">Create a new center</a>
    @endif

    @if(session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Products</th>
                <th>Users</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($centers as $center)
                <tr>
                    <td>{{ $center->name }}</td>
                    <td>{{ $center->address }}</td>
                    <td>{{ $center->city }}</td>
                    <td>{{ $center->state }}</td>
                    <td>{{ $center->zip }}</td>
                    <td><span class="badge rounded-pill bg-success">{{ $center->products->count() }}</span></td>
                    <td><span class="badge rounded-pill bg-success">{{ $center->users->count() }}</span></td>
                    <td>
                        <a class="btn btn-outline-secondary btn-sm" href="{{ route('centers.show', $center->id) }}">Show</a>
                        @if($center->id === auth()->user()->center->id || auth()->user()->isAdmin())
                            <a class="btn btn-secondary btn-sm" href="{{ route('centers.edit', $center->id) }}">Edit</a>
                            <form class="d-inline" action="{{ route('centers.destroy', $center->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <input class="btn btn-danger btn-sm" type="submit" value="Delete">
                            </form>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/centers/show.blade.php
@extends('layouts.app')

@section('title', ucfirst($center->name))

@section('content')
    <p>{{ $center->address }}</p>
    <p>{{ $center->city }}, {{ $center->state }} {{ $center->zip }}</p>

    @if(session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif

    @if($center->id === auth()->user()->center->id || auth()->user()->isAdmin())
        <a class="btn btn-primary float-end mb-4 me-2" href="{{ route('centers.products.create', $center->id) }}">Add a new product</a>
    @endif

    <h4>Products ({{ $center->products->count() }})</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($center->products as $product)
                <tr>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->price }} €</td>
                    <td>{{ $product->pivot->quantity }}</td>
                    <td>
                        <a class="btn btn-outline-secondary btn-sm" href="{{ route('products.show', $product->id) }}">Show</a>
                        @if($center->id === auth()->user()->center->id || auth()->user()->isAdmin())
                            <a class="btn btn-success btn-sm" href="{{ route('centers.products.edit', [$center->id, $product->id]) }}">Update quantity</a>
                            <a class="btn btn-info btn-sm" href="{{ route('transfers.create', ['center_id' => $center->id, 'product_id' => $product->id]) }}">Transfer</a>
                            <form class="d-inline" action="{{ route('centers.products.destroy', [$center->id, $product->id]) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <input class="btn btn-danger btn-sm" type="submit" value="Remove">
                            </form>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection