routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\CenterProductController;
use App\Http\Controllers\CentersController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\TransfersController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

Route::get('/login', [LoginController::class, 'show'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'login'])->middleware('guest');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', HomeController::class)->name('home');
    Route::resource('centers', CentersController::class);
    Route::resource('products', ProductsController::class);
    Route::resource('centers.products', CenterProductController::class)->except(['index', 'show']);
    Route::resource('transfers', TransfersController::class)->except(['show', 'edit', 'destroy']);
    Route::resource('users', UsersController::class)->except(['show', 'edit', 'update']);
    Route::post('/logout', LogoutController::class)->name('logout');
});

app/Models/Product.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'price',
        'category',
    ];

    public function transfers(): HasMany
    {
        return $this->hasMany(Transfer::class);
    }

    public function centers(): BelongsToMany
    {
        return $this->belongsToMany(Center::class)->withPivot('quantity');
    }
}

app/Http/Controllers/ProductsController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Enums\ProductCategory;
use App\Http\Middleware\Admin;
use App\Http\Requests\ProductRequest;
use App\Models\Product;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class ProductsController extends Controller
{
    public function __construct()
    {
        $this->middleware(Admin::class)->only(['create', 'store', 'edit', 'update', 'destroy']);
    }

    public function index(): View
    {
        $products = Product::orderBy('name')->paginate(10);

        return view('products.index', compact('products'));
    }

    public function show(Product $product): View
    {
        return view('products.show', compact('product'));
    }

    public function create(): View
    {
        $categories = ProductCategory::cases();

        return view('products.create', compact('categories'));
    }

    public function store(ProductRequest $request): RedirectResponse
    {
        Product::create($request->validated());

        return redirect()
            ->route('products.index')
            ->with('message', 'Product created successfully');
    }

    public function edit(Product $product): View
    {
        $categories = ProductCategory::cases();

        return view('products.edit', compact('product', 'categories'));
    }

    public function update(ProductRequest $request, Product $product): RedirectResponse
    {
        $product->update($request->validated());

        return redirect()
            ->route('products.index')
            ->with('message', 'Product updated successfully');
    }

    public function destroy(Product $product): RedirectResponse
    {
        $product->delete();

        return redirect()
            ->route('products.index')
            ->with('message', 'Product deleted successfully');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('title', "Create a new product")

@section('content')
    <form action="{{ route('products.store') }}" method="POST">
        @csrf

        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}">
            @error('name')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea class="form-control" id="description" name="description">
                {{ old('description') }}
            </textarea>
            @error('description')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="text" class="form-control" id="price" name="price" value="{{ old('price') }}">
            @error('price')
            <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="category" class="form-label">Categories</label>
            <select class="form-select" id="category" name="category">
                @foreach($categories as $category)
                    <option value="{{ $category->name }}">{{ $category->value }}</option>
                @endforeach
            </select>
            @error('categories')
                <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">Create</button>
    </form>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('title', "Edit {$product->name}")

@section('content')
    <form action="{{ route('products.update', $product->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $product->name) }}">
            @error('name')
            <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea class="form-control" id="description" name="description">
            {{ old('description', $product->description) }}
        </textarea>
            @error('description')
            <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="text" class="form-control" id="price" name="price"
                   value="{{ old('price', $product->price) }}">
            @error('price')
            <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="category" class="form-label">Categories</label>
            <select class="form-select" id="category" name="category">
                @foreach($categories as $category)
                    <option
                        value="{{ $category->name }}" {{ $category->name === $product->category ? 'selected' : '' }}>{{ $category->value }}</option>
                @endforeach
            </select>
            @error('categories')
            <div class="alert alert-danger mt-2">{{ $message }}</div>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('title', "Products ({$products->total()})")

@section('content')
    @if(auth()->user()->isAdmin())
        <a class="btn btn-primary float-end mb-4" href="{{ route('products.create') }}">Create a new product</a>
    @endif

    @if(session()->has('message'))
        <div class="alert alert-success">
            {{ session()->get('message') }}
        </div>
    @endif

    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Category</th>
                <th style="width: 650px">Description</th>
                <th>Centers</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
                <tr>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->price }} €</td>
                    <td>{{ $product->category }}</td>
                    <td>{{ $product->description }}</td>
                    <td>
                        @foreach($product->centers as $center)
                            <a href="{{ route('centers.show', $center->id) }}">{{ $center->name }}</a>
                            <span class="badge rounded-pill bg-success">{{ $center->pivot->quantity }}</span>
                            <br>
                        @endforeach
                    </td>
                    <td>
                        <a class="btn btn-outline-secondary btn-sm" href="{{ route('products.show', $product->id) }}">Show</a>
                        @if(auth()->user()->isAdmin())
                            <a class="btn btn-secondary btn-sm" href="{{ route('products.edit', $product->id) }}">Edit</a>
                            <form class="d-inline" action="{{ route('products.destroy', $product->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <input class="btn btn-danger btn-sm" type="submit" value="Delete">
                            </form>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{ $products->links("pagination::bootstrap-5") }}
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('title', $product->name)

@section('content')
    <div class="row">
        <div class="col-12">
            <p>{{ $product->description }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <p><b>Price:</b> {{ $product->price }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <p><b>Category:</b> {{ $product->category }}</p>
        </div>
    </div>

    @if(auth()->user()->isAdmin())
        <div class="row">
            <div class="col-12">
                <a href="{{ route('products.edit', $product->id) }}" class="btn btn-primary">Edit</a>
            </div>
        </div>
    @endif
@endsection